### ISSUE TITLE
idea c2 - Family Chore Chart

### ISSUE THREAD

**Issue by godwinbw** [godwinbw/cleaNest#6]

**Comment by godwinbw** [comment]
create an online "Family Chores" website.

 - can create users for each member of the family
 - can create "categories" or "rooms" for grouping tasks.  like "kitchen", "bathroom", "bedroom" etc
 - can create a task that needs to be done (like "change sheets")
 - a task can be "one time only", or can be "auto-repeat"
 - if a task is "auto-repeat", it can be set for "every day", "every other day", "once a week", "once every two weeks", or "once a month"
 - a task has a "due date"
 - a task can be assigned to a family member (it can be assigned or unassigned)
 - a family member can mark a task as complete
 - all users can view a dashboard to see all tasks for the next 7 days, and who is assigned, and the status
 - a task can be complete or incomplete (based on whether it is done or not)
 - a task can be on-time or late (based on whether or not the task is marked complete)
 - a user can see their work by clicking on their detail

extra npm tool used -> https://www.npmjs.com/package/node-cron

use node-cron to automatically generate "auto-repeat" tasks

**Comment by yygrace03** [comment]
I think this is a perfect idea!!
